""" BOARD  """
DEFAULT_FONT = ("Helvetica", 14)
BIG_FONT = ("Helvetica", 32)
BACKGROUD_COLOR = "green"

""" CARD """
# dimension
CARD_SCALE = 4
CARD_WIDTH_ORIGINAL = 500
CARD_HEIGHT_ORIGINAL = 726
CARD_WIDTH = CARD_WIDTH_ORIGINAL // CARD_SCALE
CARD_HEIGHT = CARD_HEIGHT_ORIGINAL // CARD_SCALE

""" HAND """
MAX_CARD = 5
PAD = 20
